const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const {
  stockLevelToApi,
  stockMovementToApi,
  journalEntryToApi,
  journalLineToApi,
  accountBalanceToApi,
  inventoryBatchToApi,
  reorderPointToApi,
  accountingPeriodToApi,
} = require('../utils/inventoryJournalMappers');

describe('Phase 3+4 inventory/journal mappers', () => {
  test('stockLevelToApi preserves snake_case and qty_available virtual', () => {
    const api = stockLevelToApi({
      id: 'sl1',
      companyId: 'c1',
      productId: 'p1',
      warehouseId: 'w1',
      qtyOnHand: { toString: () => '100.0000' },
      qtyReserved: { toString: () => '20.0000' },
      qtyOnOrder: 0,
      avgCost: 5.5,
      totalValue: 550,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    expect(api.company_id).toBe('c1');
    expect(api.qty_on_hand).toBe(100);
    expect(api.qty_available).toBe(80);
  });

  test('stockMovementToApi dual company/product refs and decimal strings', () => {
    const api = stockMovementToApi({
      id: 'm1',
      companyId: 'c1',
      productId: 'p1',
      type: 'in',
      reason: 'purchase',
      quantity: { toString: () => '10.0000' },
      previousStock: 0,
      newStock: 10,
      unitCost: { toString: () => '5.500000' },
      totalCost: 55,
      movementDate: new Date(),
      ebm: {},
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    expect(api.company).toBe('c1');
    expect(api.company_id).toBe('c1');
    expect(api.quantity).toBe('10.0000');
    expect(api.unitCost).toBe('5.50');
  });

  test('journalEntryToApi embeds lines from child rows', () => {
    const api = journalEntryToApi({
      id: 'je1',
      companyId: 'c1',
      entryNumber: 'JE-ABC-2026-1',
      date: new Date(),
      description: 'Test',
      status: 'posted',
      totalDebit: { toString: () => '100.00' },
      totalCredit: { toString: () => '100.00' },
      isAutoGenerated: false,
      reversed: false,
      reconciliationStatus: 'unreconciled',
      isLocked: false,
      isReconciliationAdjustingEntry: false,
      createdById: 'u1',
      lines: [
        {
          lineOrder: 0,
          accountCode: '1000',
          accountName: 'Cash',
          debit: 100,
          credit: 0,
          reconciled: false,
        },
        {
          lineOrder: 1,
          accountCode: '4000',
          accountName: 'Revenue',
          debit: 0,
          credit: 100,
          reconciled: false,
        },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    expect(api.lines).toHaveLength(2);
    expect(api.lines[0].debit).toBe('100.00');
    expect(api.debitTotal).toBe('100.00');
  });

  test('journalLineToApi money formatting', () => {
    const line = journalLineToApi({ accountCode: '1000', accountName: 'Cash', debit: 50.5, credit: 0 });
    expect(line.debit).toBe('50.50');
  });

  test('accountBalanceToApi net virtual', () => {
    const api = accountBalanceToApi({
      id: 'ab1',
      companyId: 'c1',
      accountCode: '1000',
      debit: 100,
      credit: 30,
      updatedAt: new Date(),
    });
    expect(api.net).toBe(70);
  });

  test('inventoryBatchToApi maps quantities', () => {
    const api = inventoryBatchToApi({
      id: 'b1',
      companyId: 'c1',
      productId: 'p1',
      warehouseId: 'w1',
      quantity: 50,
      availableQuantity: 40,
      reservedQuantity: 10,
      unitCost: 2,
      totalCost: 100,
      status: 'active',
      receivedDate: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    expect(api.availableQuantity).toBe(40);
  });

  test('reorderPointToApi maps product/supplier', () => {
    const api = reorderPointToApi({
      id: 'rp1',
      companyId: 'c1',
      productId: 'p1',
      supplierId: 's1',
      reorderPoint: 10,
      reorderQuantity: 50,
      safetyStock: 5,
      leadTimeDays: 7,
      autoReorder: true,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    expect(api.reorderPoint).toBe(10);
  });

  test('accountingPeriodToApi snake_case fields', () => {
    const api = accountingPeriodToApi({
      id: 'ap1',
      companyId: 'c1',
      name: 'July 2026',
      periodType: 'month',
      startDate: new Date('2026-07-01'),
      endDate: new Date('2026-07-31'),
      fiscalYear: 2026,
      status: 'open',
      isYearEnd: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
    expect(api.company_id).toBe('c1');
    expect(api.period_type).toBe('month');
  });
});

describe('Phase 3+4 Neon integration', () => {
  const hasDb = Boolean(process.env.DATABASE_URL);

  (hasDb ? test : test.skip)('stock_movements list query uses indexed company_id + movement_date', async () => {
    const { prisma, connectPrisma, disconnectPrisma } = require('../lib/prisma');
    await connectPrisma();
    const company = await prisma.company.findFirst({ select: { id: true } });
    expect(company).toBeTruthy();
    const rows = await prisma.stockMovement.findMany({
      where: { companyId: company.id },
      orderBy: { movementDate: 'desc' },
      take: 5,
    });
    expect(Array.isArray(rows)).toBe(true);
    await disconnectPrisma();
  });

  (hasDb ? test : test.skip)('journal_entries list query with lines include', async () => {
    const { prisma, connectPrisma, disconnectPrisma } = require('../lib/prisma');
    await connectPrisma();
    const company = await prisma.company.findFirst({ select: { id: true } });
    const rows = await prisma.journalEntry.findMany({
      where: { companyId: company.id },
      orderBy: [{ date: 'desc' }, { entryNumber: 'desc' }],
      take: 3,
      include: { lines: { orderBy: { lineOrder: 'asc' }, take: 10 } },
    });
    expect(Array.isArray(rows)).toBe(true);
    await disconnectPrisma();
  });

  (hasDb ? test : test.skip)('account_balances unique lookup by company + code', async () => {
    const { prisma, connectPrisma, disconnectPrisma } = require('../lib/prisma');
    await connectPrisma();
    const count = await prisma.accountBalance.count();
    expect(count).toBeGreaterThanOrEqual(0);
    await disconnectPrisma();
  });
});
