const FreightBill = require('../models/FreightBill');
const GoodsReceivedNote = require('../models/GoodsReceivedNote');
const JournalService = require('../services/journalService');
const { DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');
const transactionService = require('../services/transactionService');
const { decimalToNumber } = require('../utils/decimalHelpers');

// Helper: resolve credit account for payment method
function resolveCreditAccount(paymentMethod) {
  if (paymentMethod === 'cash') return DEFAULT_ACCOUNTS.cashInHand || '1000';
  if (paymentMethod === 'bank_transfer') return DEFAULT_ACCOUNTS.cashAtBank || '1100';
  if (paymentMethod === 'mobile_money') return DEFAULT_ACCOUNTS.mtnMoMo || '1200';
  return DEFAULT_ACCOUNTS.accountsPayable || '2000';
}

function resolveCompanyId(req) {
  return req.user?.company?._id || req.user?.company || req.user?.companyId || null;
}

/** Goods value from GRN lines, with totalAmount fallback when lines are missing/zero. */
function computeGrnGoodsValue(grn) {
  const lines = Array.isArray(grn?.lines) ? grn.lines : [];
  const fromLines = lines.reduce((sum, line) => {
    const qty = decimalToNumber(line.qtyReceived ?? line.qty, 0);
    const unitCost = decimalToNumber(line.unitCost, 0);
    const lineTotal = decimalToNumber(line.lineTotal ?? line.totalWithTax, 0);
    return sum + (qty * unitCost || lineTotal);
  }, 0);
  if (fromLines > 0) return fromLines;
  return decimalToNumber(grn?.totalAmount ?? grn?.subtotal, 0);
}

// Create freight bill
exports.createFreightBill = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const payload = req.body;
    payload.company = companyId;
    payload.createdBy = req.user.id;
    payload.status = 'draft';

    const fb = await FreightBill.create(payload);
    res.status(201).json({ success: true, data: fb });
  } catch (err) { next(err); }
};

// Update freight bill (draft only)
exports.updateFreightBill = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const fb = await FreightBill.findOne({ _id: req.params.id, company: companyId });
    if (!fb) return res.status(404).json({ success: false, message: 'Freight bill not found' });
    if (fb.status !== 'draft') return res.status(409).json({ success: false, message: 'Only draft freight bills can be edited' });

    const allowed = ['referenceNo', 'supplier', 'carrierName', 'amount', 'account', 'invoiceDate', 'paymentMethod', 'grnMatches'];
    for (const field of allowed) {
      if (req.body[field] !== undefined) fb[field] = req.body[field];
    }
    await fb.save();
    res.json({ success: true, data: fb });
  } catch (err) { next(err); }
};

// Confirm freight bill -> post journal entry
exports.confirmFreightBill = async (req, res, next) => {
  const companyId = req.user.company._id;

  const runConfirm = async (sess) => {
    const useSession = !!sess;
    const findOpts = useSession ? { session: sess } : {};

    const fb = await FreightBill.findOne({ _id: req.params.id, company: companyId }, null, findOpts);
    if (!fb) throw Object.assign(new Error('Freight bill not found'), { status: 404 });
    if (fb.status === 'confirmed') throw Object.assign(new Error('Freight bill already confirmed'), { status: 400 });

    const freightAcct = fb.account || DEFAULT_ACCOUNTS.freightIn || '5110';
    const creditAcct = resolveCreditAccount(fb.paymentMethod);
    const narration = `Freight Bill ${fb.referenceNo}${fb.carrierName ? ' - ' + fb.carrierName : ''}`;

    const journalLines = [
      JournalService.createDebitLine(freightAcct, fb.amount, narration),
      JournalService.createCreditLine(creditAcct, fb.amount, narration),
    ];

    const created = await JournalService.createEntriesAtomic(
      companyId,
      req.user.id,
      [{
        date: fb.invoiceDate || new Date(),
        description: narration,
        sourceType: 'freight_bill',
        sourceId: fb._id,
        sourceReference: fb.referenceNo,
        lines: journalLines,
        isAutoGenerated: true,
        session: useSession ? sess : null,
      }],
      { session: useSession ? sess : null },
    );
    const je = created && created.length ? created[0] : null;

    fb.status = 'confirmed';
    fb.confirmedBy = req.user.id;
    fb.confirmedAt = new Date();
    fb.journalEntry = je._id;
    await fb.save(useSession ? { session: sess } : {});

    // If GRN matches provided, update GRN freight references (optional linking)
    if (fb.grnMatches && fb.grnMatches.length > 0) {
      for (const match of fb.grnMatches) {
        await GoodsReceivedNote.updateOne(
          { _id: match.grn, company: companyId },
          { $set: { 'freight.actualAmount': match.amountAllocated } },
          { session: sess || null },
        );
      }
    }

    return fb;
  };

  try {
    const result = await transactionService.runInTransaction(async (trx) => await runConfirm(trx));
    res.json({ success: true, data: result });
  } catch (err) {
    if (err && err.status) return res.status(err.status).json({ success: false, message: err.message });
    next(err);
  }
};

// List freight bills
exports.listFreightBills = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const { status, page = 1, limit = 20 } = req.query;
    const query = { company: companyId };
    if (status) query.status = status;

    const skip = (parseInt(page) - 1) * parseInt(limit);
    const bills = await FreightBill.find(query)
      .populate('supplier', 'name code')
      .populate('grnMatches.grn', 'referenceNo')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(parseInt(limit))
      .lean();

    const total = await FreightBill.countDocuments(query);
    res.json({ success: true, data: bills, pagination: { page: parseInt(page), limit: parseInt(limit), total } });
  } catch (err) { next(err); }
};

// Get single freight bill
exports.getFreightBill = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const fb = await FreightBill.findOne({ _id: req.params.id, company: companyId })
      .populate('supplier', 'name code')
      .populate('grnMatches.grn', 'referenceNo receivedDate')
      .populate('journalEntry', 'entryNumber date')
      .lean();
    if (!fb) return res.status(404).json({ success: false, message: 'Freight bill not found' });
    res.json({ success: true, data: fb });
  } catch (err) { next(err); }
};

// Freight Cost Analysis
exports.getFreightAnalysis = async (req, res, next) => {
  try {
    const companyId = resolveCompanyId(req);
    if (!companyId) {
      return res.status(400).json({ success: false, message: 'Company context required' });
    }
    const { date_from, date_to, supplier_id } = req.query;

    const match = { company: companyId, status: 'confirmed' };
    if (date_from || date_to) {
      match.confirmedAt = {};
      if (date_from) match.confirmedAt.$gte = new Date(date_from);
      if (date_to) match.confirmedAt.$lte = new Date(date_to);
    }
    if (supplier_id) match.supplier = supplier_id;

    // Aggregate freight bills per supplier
    const perSupplier = await FreightBill.aggregate([
      { $match: match },
      { $group: { _id: '$supplier', totalFreight: { $sum: '$amount' }, billCount: { $sum: 1 } } },
      { $lookup: { from: 'suppliers', localField: '_id', foreignField: '_id', as: 'supplierDoc' } },
      { $unwind: { path: '$supplierDoc', preserveNullAndEmptyArrays: true } },
      { $project: { supplierName: { $ifNull: ['$supplierDoc.name', 'Unknown'] }, totalFreight: 1, billCount: 1 } },
    ]);

    // GRN-level analysis — always include lines (needed for goods value)
    const grnQuery = { company: companyId, status: 'confirmed' };
    if (date_from || date_to) {
      grnQuery.confirmedAt = {};
      if (date_from) grnQuery.confirmedAt.$gte = new Date(date_from);
      if (date_to) grnQuery.confirmedAt.$lte = new Date(date_to);
    }

    const grns = await GoodsReceivedNote.find(grnQuery)
      .populate('supplier', 'name')
      .populate('purchaseOrder', 'referenceNo')
      .populate('lines')
      .lean();

    const grnAnalysis = grns.map((grn) => {
      const goodsValue = computeGrnGoodsValue(grn);
      const freightAmt = decimalToNumber(grn.freight?.actualAmount, 0);
      return {
        grnId: grn._id,
        referenceNo: grn.referenceNo,
        supplierName: grn.supplier?.name || 'N/A',
        poReference: grn.purchaseOrder?.referenceNo || 'N/A',
        goodsValue,
        freightAmount: freightAmt,
        freightPct: goodsValue > 0 ? (freightAmt / goodsValue) * 100 : 0,
        hasFreight: freightAmt > 0,
        receivedDate: grn.receivedDate,
      };
    });

    const totalFreight = perSupplier.reduce((s, r) => s + decimalToNumber(r.totalFreight, 0), 0);
    const totalGoodsValue = grnAnalysis.reduce((s, r) => s + r.goodsValue, 0);
    const flaggedGRNs = grnAnalysis.filter((g) => !g.hasFreight);

    res.json({
      success: true,
      data: {
        summary: {
          totalFreight,
          totalGoodsValue,
          overallFreightPct: totalGoodsValue > 0 ? (totalFreight / totalGoodsValue) * 100 : 0,
          grnCount: grnAnalysis.length,
          flaggedGRNCount: flaggedGRNs.length,
        },
        perSupplier,
        perGRN: grnAnalysis,
        flaggedGRNs,
      },
    });
  } catch (err) { next(err); }
};

// Delete freight bill (draft only)
exports.deleteFreightBill = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const fb = await FreightBill.findOne({ _id: req.params.id, company: companyId });
    if (!fb) return res.status(404).json({ success: false, message: 'Freight bill not found' });
    if (fb.status !== 'draft') return res.status(409).json({ success: false, message: 'Only draft freight bills can be deleted' });
    await fb.deleteOne();
    res.json({ success: true, message: 'Freight bill deleted' });
  } catch (err) { next(err); }
};
