ALTER TABLE "delivery_note_lines"
  ADD COLUMN "discount_pct" DECIMAL(19,4) NOT NULL DEFAULT 0,
  ADD COLUMN "tax_rate" DECIMAL(19,4) NOT NULL DEFAULT 0,
  ADD COLUMN "tax_code" TEXT NOT NULL DEFAULT 'A',
  ADD COLUMN "line_subtotal" DECIMAL(19,2) NOT NULL DEFAULT 0,
  ADD COLUMN "line_tax" DECIMAL(19,2) NOT NULL DEFAULT 0;
