ALTER TABLE ar_receipts
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMPTZ(3),
  ADD COLUMN IF NOT EXISTS reversed_by CHAR(24),
  ADD COLUMN IF NOT EXISTS reversal_reason TEXT;
