CREATE TABLE "system_settings" (
  "id" CHAR(24) NOT NULL,
  "company_id" CHAR(24) NOT NULL,
  "invoice_prefix" TEXT NOT NULL DEFAULT 'INV',
  "invoice_footer_text" TEXT,
  "invoice_payment_instructions" TEXT,
  "default_invoice_due_days" INTEGER NOT NULL DEFAULT 30,
  "default_quote_expiry_days" INTEGER NOT NULL DEFAULT 30,
  "auto_apply_vat" BOOLEAN NOT NULL DEFAULT false,
  "default_vat_rate_id" CHAR(24),
  "default_costing_method" TEXT NOT NULL DEFAULT 'fifo',
  "allow_negative_stock" BOOLEAN NOT NULL DEFAULT false,
  "low_stock_alert_enabled" BOOLEAN NOT NULL DEFAULT true,
  "auto_reorder_enabled" BOOLEAN NOT NULL DEFAULT true,
  "auto_reorder_create_documents" BOOLEAN NOT NULL DEFAULT true,
  "auto_reorder_safety_stock_days" INTEGER NOT NULL DEFAULT 7,
  "auto_reorder_sales_lookback_days" INTEGER NOT NULL DEFAULT 90,
  "auto_reorder_direct_purchase_threshold" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "auto_reorder_created_by" CHAR(24),
  "require_po_approval" BOOLEAN NOT NULL DEFAULT true,
  "po_approval_threshold" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "require_invoice_approval" BOOLEAN NOT NULL DEFAULT false,
  "document_terms_and_conditions" TEXT,
  "document_theme_color" TEXT NOT NULL DEFAULT '#1D9E75',
  "notify_on_low_stock" BOOLEAN NOT NULL DEFAULT true,
  "notify_on_overdue_invoice" BOOLEAN NOT NULL DEFAULT true,
  "overdue_invoice_alert_days" INTEGER NOT NULL DEFAULT 7,
  "last_updated_by" CHAR(24),
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "system_settings_company_id_key" ON "system_settings"("company_id");
