/**
 * JournalEntry — PostgreSQL (Prisma) backed.
 * Lines in journal_entry_lines; API keeps embedded lines[] for compatibility.
 */

const mongoose = require('mongoose');
const { prisma } = require('../lib/prisma');
const { makeCompatModel, toId } = require('../utils/prismaCompat');
const { decimalToNumber } = require('../utils/decimalHelpers');
const { runInPrismaTransaction } = require('../services/transactionService');
const {
  journalEntryToApi,
  journalEntryTranslateCreate,
  journalEntryTranslateUpdate,
  linesToPrismaCreate,
} = require('../utils/inventoryJournalMappers');
const { applyJournalLinesToAccountBalances } = require('../utils/accountBalanceSync');
const { bumpFinancialCaches } = require('../utils/journalEntryPosting');

const FIELD_MAP = {
  _id: { target: 'id', isId: true },
  id: { target: 'id', isId: true },
  company: { target: 'companyId', isId: true },
  companyId: { target: 'companyId', isId: true },
  entryNumber: { target: 'entryNumber' },
  date: { target: 'date' },
  description: { target: 'description' },
  sourceType: { target: 'sourceType' },
  sourceId: { target: 'sourceId' },
  sourceReference: { target: 'sourceReference' },
  reference: { target: 'reference' },
  status: { target: 'status' },
  isAutoGenerated: { target: 'isAutoGenerated' },
  reversalOf: { target: 'reversalOfId', isId: true },
  createdBy: { target: 'createdById', isId: true },
  postedBy: { target: 'postedById', isId: true },
  isLocked: { target: 'isLocked' },
  reconciliationStatus: { target: 'reconciliationStatus' },
  createdAt: { target: 'createdAt' },
  updatedAt: { target: 'updatedAt' },
};

const LINE_INCLUDE = { lines: { orderBy: { lineOrder: 'asc' } } };

if (!mongoose.models.JournalEntry) {
  mongoose.model('JournalEntry', new mongoose.Schema({}, { strict: false, collection: 'journalentries' }));
}

function JournalEntryDoc(data = {}) {
  Object.assign(this, data);
  if (!this.lines) this.lines = [];
  this.isNew = !this._id;
}

JournalEntryDoc.prototype.save = async function save() {
  if (this.isLocked) {
    throw new Error('Cannot modify a locked journal entry. This entry has been reconciled and is locked for audit trail integrity.');
  }

  if (this.isNew || !this._id) {
    const createData = await journalEntryTranslateCreate(this);
    const row = await prisma.journalEntry.create({ data: createData, include: LINE_INCLUDE });
    Object.assign(this, journalEntryToApi(row));
    this.isNew = false;

    if (this.status === 'posted' && !this.reversed) {
      await applyJournalLinesToAccountBalances(
        this.company || this.companyId,
        this.lines || [],
        1,
      );
      await bumpFinancialCaches(this.company || this.companyId);
    }

    return this;
  }

  const existing = await prisma.journalEntry.findUnique({
    where: { id: String(this._id) },
    select: { status: true, isLocked: true },
  });
  if (existing?.isLocked) {
    throw new Error('Cannot modify a locked journal entry. This entry has been reconciled and is locked for audit trail integrity.');
  }
  if (existing?.status === 'posted') {
    throw new Error('Cannot modify a posted journal entry');
  }

  const prevStatus = existing?.status;

  const headerUpdate = journalEntryTranslateUpdate({ $set: this });
  if (Array.isArray(this.lines)) {
    const sumDebit = this.lines.reduce((s, l) => s + decimalToNumber(l.debit, 0), 0);
    const sumCredit = this.lines.reduce((s, l) => s + decimalToNumber(l.credit, 0), 0);
    headerUpdate.totalDebit = sumDebit.toFixed(2);
    headerUpdate.totalCredit = sumCredit.toFixed(2);
    headerUpdate.debitTotal = headerUpdate.totalDebit;
    headerUpdate.creditTotal = headerUpdate.totalCredit;
  }

  const row = await runInPrismaTransaction(async (tx) => {
    await tx.journalEntry.update({ where: { id: String(this._id) }, data: headerUpdate });
    if (Array.isArray(this.lines)) {
      await tx.journalEntryLine.deleteMany({ where: { journalEntryId: String(this._id) } });
      const lineRows = linesToPrismaCreate(String(this.company || this.companyId), this.lines).map((l) => ({
        ...l,
        journalEntryId: String(this._id),
      }));
      if (lineRows.length) await tx.journalEntryLine.createMany({ data: lineRows });
    }
    return tx.journalEntry.findUnique({ where: { id: String(this._id) }, include: LINE_INCLUDE });
  });

  Object.assign(this, journalEntryToApi(row));

  if (prevStatus !== 'posted' && this.status === 'posted' && !this.reversed) {
    await applyJournalLinesToAccountBalances(
      this.company || this.companyId,
      this.lines || [],
      1,
    );
    await bumpFinancialCaches(this.company || this.companyId);
  }

  return this;
};

JournalEntryDoc.prototype.isBalanced = function isBalanced() {
  const td = decimalToNumber(this.totalDebit, 0);
  const tc = decimalToNumber(this.totalCredit, 0);
  return Math.abs(td - tc) < 0.01;
};

const base = makeCompatModel({
  delegate: () => prisma.journalEntry,
  fieldMap: FIELD_MAP,
  toApi: journalEntryToApi,
  translateCreate: journalEntryTranslateCreate,
  translateUpdate: journalEntryTranslateUpdate,
  include: () => LINE_INCLUDE,
  tenantField: 'companyId',
});

function JournalEntry(data) {
  if (!(this instanceof JournalEntry)) return new JournalEntryDoc(data);
  return JournalEntryDoc.call(this, data);
}

Object.assign(JournalEntry, base);

JournalEntry.prototype = JournalEntryDoc.prototype;

JournalEntry.create = async function create(data) {
  const status = data?.status || 'draft';
  const lines = Array.isArray(data?.lines) ? data.lines : [];
  const companyId = data?.company || data?.companyId;
  const userId =
    data?.createdBy
    || data?.postedBy
    || data?.createdById
    || data?.postedById;

  // Route auto-posted entries through JournalService for idempotency, tax/bank hooks, and cache.
  if (status === 'posted' && lines.length >= 2 && companyId && userId) {
    const JournalService = require('../services/journalService');
    const skipBank =
      data.skipBankTransactions === true
      || data._skipAutoBankSync === true
      || (data.skipBankTransactions !== false && data.bankAccountId == null && !data.sourceData?.bankAccountId);

    return JournalService.createEntry(companyId, userId, {
      date: data.date,
      description: data.description,
      sourceType: data.sourceType || 'manual',
      sourceId: data.sourceId,
      sourceReference: data.sourceReference || data.reference,
      lines,
      isAutoGenerated: data.isAutoGenerated,
      notes: data.notes,
      allowDuplicate: data.allowDuplicate,
      skipBankTransactions: skipBank,
      bankAccountId: data.bankAccountId,
      transferFromAccountId: data.transferFromAccountId,
      transferToAccountId: data.transferToAccountId,
      sourceData: data.sourceData,
      session: data.session,
    });
  }

  const doc = new JournalEntryDoc(data);
  return doc.save();
};

JournalEntry.generateEntryNumber = async function generateEntryNumber(companyId) {
  const { nextSequence } = require('../services/sequenceService');
  const year = new Date().getFullYear();
  const seq = await nextSequence(companyId, 'journal_entry');
  return `JE-${String(companyId).slice(-4).toUpperCase()}-${year}-${seq}`;
};

JournalEntry.getTrialBalance = async function getTrialBalance(companyId, startDate, endDate) {
  const entries = await prisma.journalEntry.findMany({
    where: {
      companyId: String(companyId),
      status: 'posted',
      date: { gte: startDate, lte: endDate },
    },
    include: LINE_INCLUDE,
  });
  const accountBalances = {};
  for (const entry of entries) {
    for (const line of entry.lines || []) {
      const code = line.accountCode;
      if (!accountBalances[code]) {
        accountBalances[code] = { code, name: line.accountName, debit: 0, credit: 0, balance: 0 };
      }
      accountBalances[code].debit += decimalToNumber(line.debit, 0);
      accountBalances[code].credit += decimalToNumber(line.credit, 0);
    }
  }
  Object.values(accountBalances).forEach((a) => { a.balance = a.debit - a.credit; });
  return accountBalances;
};

module.exports = JournalEntry;
